[package]
name = "cli"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-std = { version = "1.12.0", features = ["std", "attributes"] }
async-task-group = "0.2.1"
futures = "0.3"
bcs = "0.1.5"
clap = { version = "4.1.8", features = ["derive"] }
crossbeam-channel = "0.5.7"
eyre = "0.6.8"
serde = { workspace = true, features = ["derive"] }
shared = { path = "../shared" }
surf = "2.3.2"
