name = "Hello World"
description = "A Hello World core, and a _very_ simple counter core, which is wrapped with multiple shells"
authors = ["Red Badger Consulting Limited"]
repository = "https://github.com/redbadger/crux/"

[cores.shared]
source = "shared"
type_gen = "shared_types"
crux_version = "0.6.3"
