[package]
publish = false
name = "crux_cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[[bin]]
name = "crux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.35", features = ["derive"] }
console = "0.15.11"
ignore = "0.4.23"
ramhorns = "1.0.1"
serde = { workspace = true, features = ["derive"] }
similar = { version = "2.7.0", features = ["inline"] }
toml = "0.8.20"
