[package]
publish = false
name = "crux_cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version = "1.70"

[[bin]]
name = "crux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.35", features = ["derive"] }
console = "0.15.11"
guppy = "0.17.5"
ignore = "0.4.23"
libc = "0.2.155"
ramhorns = "1.0.0"
rustdoc-types = "0.24.0"
serde = { workspace = true, features = ["derive"] }
similar = { version = "2.7.0", features = ["inline"] }
toml = "0.8.20"
serde_json = "1.0.114"
tokio = { version = "1.37.0", features = ["full"] }
tokio-fd = "0.3.0"
