[package]
publish = false
name = "crux_cli"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version = "1.70"

[[bin]]
name = "crux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.35", features = ["derive"] }
console = "0.15.11"
guppy = "0.17.5"
ascent = "0.7.0"
env_logger = "0.10.2"
ignore = "0.4.23"
iter_tools = "0.24.0"
lazy-regex = "3.3.0"
libc = "0.2.167"
log = "0.4.22"
ramhorns = "1.0.1"
rustdoc-json = "0.9.3"
rustdoc-types = "0.33.0"
serde = { workspace = true, features = ["derive"] }
similar = { version = "2.7.0", features = ["inline"] }
toml = "0.8.20"
serde_json = "1.0.133"
thiserror = "2.0.5"
tokio = { version = "1.42.0", features = ["full"] }
tokio-fd = "0.3.0"

[dev-dependencies]
insta = { version = "1.41.1" }
pretty_assertions = "1.4.1"
rstest = "0.23.0"
