[package]
name = "crux_http"
description = "HTTP capability for use with crux_core"
version = "0.1.0"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
crux_core = { version = "0.2", path = "../crux_core" }
derive_more = "0.99.17"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.91"
url = "2.3.1"

[dev-dependencies]
crux_macros = { version = "0.1", path = "../crux_macros" }
