[package]
name = "web-yew"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
gloo-console = "0.2.3"
gloo-net = { version = "0.3.1", features = ["http"] }
js-sys = "0.3.64"
shared = { path = "../shared" }
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["Navigator"] }
woothee = "0.13.0"
yew = { version = "0.20.0", features = ["csr"] }
