[package]
name = "web-yew"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
gloo-console = "0.3.0"
gloo-net = { version = "0.6.0", features = ["http"] }
js-sys = "0.3.77"
shared = { path = "../shared" }
web-sys = { version = "0.3.77", features = ["Navigator"] }
woothee = "0.13.0"
yew = { version = "0.21.0", features = ["csr"] }
