[package]
name = "web-yew"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bcs = "0.1.4"
gloo-net = { version = "0.2.5", features = ["http"] }
js-sys = "0.3.60"
shared = { path = "../shared" }
wasm-bindgen-futures = "0.4.33"
web-sys = { version = "0.3.60", features = ["Navigator"] }
woothee = "0.13.0"
yew = { version = "0.20.0", features = ["csr"] }
