[package]
name = "web-yew"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
futures-util = "0.3.28"
gloo-net = { version = "0.2.6", features = ["http"] }
js-sys = "0.3.63"
shared = { path = "../shared" }
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
wasm-streams = "0.3.0"
yew = { version = "0.20.0", features = ["csr"] }
futures = "0.3.28"
