[package]
name = "crux_macros"
description = "Macros for use with crux_core"
version = "0.4.3"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.82"

[dev-dependencies]
crux_core = { path = "../crux_core" }
crux_http = { path = "../crux_http" }
insta = "1.40"
prettyplease = "0.2"
serde = { version = "1.0.213", features = ["derive"] }
